# Site-wide metadata
name: TimurTripp.com
author: Timur Tripp
description: 'Timur Tripp is a web-focused software enginner based in the Denver metropolitan area.'
keywords: ['software engineer', 'web developer', 'personal website', 'portfolio', 'project', 'projects', 'project showcase']
authorBio: 'I’m a web-focused software enginner based in the Denver metropolitan area.'
authorTagline: Software engineer
email: 'timur@timurtripp.com'
sections: # Sections of the site navigation
  home:
    name: Home
    url: '/'
  portfolio:
    name: Portfolio
    url: '/portfolio'
  # archive:
  #   name: Archive
  #   url: '/archive'
