# Site-wide metadata
name: TimurTripp.com
author: Timur Tripp
description: 'Timur Tripp is a software enginner and graduate stuent based in Denver, Colorado.'
keywords: ['software engineer', 'web developer', 'personal website', 'portfolio', 'project', 'projects', 'project showcase']
authorBio: 'I’m a software enginner and graduate student based in Denver, Colorado.'
authorTagline: Software engineer
email: 'timur@timurtripp.com'
sections: # Sections of the site navigation
  home:
    name: Home
    url: '/'
  portfolio:
    name: Portfolio
    url: '/portfolio'
  # archive:
  #   name: Archive
  #   url: '/archive'
